app/controllers/login.js, migrations/20160912145044_setup.js
=> Us42 - On login, users should see their name

app/controllers/login.js, app/controllers/user.js, app/lib/authentication.js, app/middleware/authentication.js, app/routes/user.js, config/test.js, package.json, seeds/test_data.js, seeds/test_data.json, test/authentication_test.js, test/user_test.js
- Update endpoint for users. Only supports email
- Tests for GET
- Tests for PUT
Approvals:
=> US44 - Users can update their email

app/controllers/keyword_type.js, app/routes/api.js, app/routes/keyword_type.js, package.json, test/keyword_type_test.js
I need help on getting the latest chai and mocha. I've only followed a tutorial and that's how I got those versions.
=> Keywordtype endpoint

app/models/annotation.js, app/models/annotation_status.js, app/models/comment_annotation.js, app/models/gene_gene_annotation.js, app/models/gene_term_annotation.js, app/models/publication.js, migrations/20161214182144_setup.js, package.json, seeds/test_data.js, seeds/test_data.json, test/models_test.js
=> Annotation models

app/lib/uniprot_api.js, test/uniprot_api_test.js
Closes #8 
We may need to revisit this in the future if we need additional functionality.
I had some spare time so I implemented what I thought we'll need later.
=> Uniprot api

app/controllers/annotation.js, app/routes/annotation.js, app/routes/api.js, package.json, test/annotation_test.js
Closes #20 
I ended up doing Status, User, and Keyword verification on top of the Publication ID validation.
When reviewing, please be on the lookout for any cases the tests don't cover.
=> Basic submission endpoint

app/controllers/annotation_status.js, app/routes/annotation_status.js, app/routes/api.js, test/annotation_status_test.js
=> Annotation status endpoint

app/controllers/gene.js, app/routes/api.js, app/routes/gene.js, test/gene_test.js
=> Gene lookup endpoint

app/controllers/publication.js, app/lib/publication_id_validator.js, app/routes/api.js, app/routes/publication.js, test/publication_test.js
=> Publication id endpoint

app/controllers/keyword.js, app/routes/api.js, app/routes/keyword.js, test/keyword_test.js
=> Keyword suggestion

app/controllers/keyword.js
=> Fix Keyword controller reporting internal errors to clients

app/controllers/gene.js, app/lib/locus_submission_helper.js, app/lib/ncbi_api.js, app/lib/rna_central_api.js, app/lib/tair_api.js, app/lib/uniprot_api.js, app/models/external_source.js, app/models/gene_symbol.js, app/models/locus.js, app/models/locus_name.js, app/models/taxon.js, app/routes/gene.js, migrations/20170206142200_setup.js, package.json, seeds/test_data.js, seeds/test_data.json, test/controllers/gene_test.js, test/lib/models_test.js, test/lib/ncbi_api_test.js, test/lib/rna_central_api_test.js, test/lib/submission_helper_test.js, test/lib/tair_api_test.js, test/lib/uniprot_api_test.js
closes #55 
closes #54 
closes #43 
closes #56 
Yeah.....
=> Locus submission

app/controllers/dev_only.js, app/routes/api.js
=> Dev-only endpoint for making a user with all roles

app/controllers/keyword.js, app/routes/keyword.js, test/controllers/keyword_test.js
=> Keyword search fix

app/controllers/keyword.js, seeds/test/test_data.json, test/controllers/keyword_test.js
=> Remove letter-only filter from keyword search

app/controllers/submission.js, app/lib/locus_submission_helper.js, migrations/20170206142200_setup.js
=> Make fullname and symbol optional fields for a gene

app/controllers/submission.js, app/lib/annotation_submission_helper.js, app/lib/locus_submission_helper.js, app/models/annotation.js, app/models/gene_gene_annotation.js, app/models/gene_term_annotation.js, test/controllers/submission_test.js, test/lib/models_test.js, test/lib/submission_helper_test.js
=> Annotation genesymbol ref

app/controllers/draft.js, app/lib/responses.js, app/routes/draft.js, seeds/test/test_data.js, seeds/test/test_data.json, test/controllers/draft_test.js
=> Draft endpoint

app/controllers/submission.js, app/lib/annotation_submission_helper.js, migrations/20170206142200_setup.js, test/controllers/submission_test.js, test/lib/submission_helper_test.js
=> Duplicate keyword bug

app/services/obo_importer/gene_ontology_importer.js, migrations/20170206142200_setup.js, test/lib/obo_importer_test.js, test/lib/test_terms_update.obo
=> Handle obsolete keywords

app/controllers/annotation_status.js, app/controllers/gene.js, app/controllers/keyword_type.js, app/controllers/login.js, app/controllers/publication.js, app/controllers/role.js, app/controllers/submission.js, app/controllers/user.js, app/lib/annotation_submission_helper.js, app/lib/locus_submission_helper.js, app/models/external_source.js, app/models/gene_symbol.js, app/models/keyword.js, app/models/keyword_type.js, app/models/locus.js, app/models/locus_name.js, app/models/publication.js, app/models/taxon.js, test/lib/models_test.js, test/lib/submission_helper_test.js
Needed to do this mainly because the submission endpoint was a complete disaster, making bug fixes very difficult.
Ended up going through the other controllers and doing a little documentation improvement too.
=> Refactor bookshelf

app/lib/annotation_submission_helper.js, app/models/gene_symbol.js, migrations/20170206142200_setup.js, test/controllers/submission_test.js
=> Optional symbol fix

app/controllers/submission.js, test/controllers/submission_test.js
=> Increase submission search limit from 20 to 200

app/lib/responses.js
=> Print internal server errors when testing

app/controllers/keyword.js, package.json, test/controllers/keyword_test.js
=> Ignore obsolete keywords

app/models/synonym.js, app/services/obo_importer/gene_ontology_importer.js, test/lib/obo_importer_test.js, test/lib/test_terms_update.obo
=> Obo updates

package.json, seeds/prod_data.js
=> Idempotent seed

app/controllers/login.js
=> Report orcid errors when we get them

app/services/assign_roles_cli.js, package.json
=> Role assigner

app/services/obo_importer/obo_importer.js, test/lib/obo_importer_test.js
=> Graceful obo error

app/controllers/login.js
=> Assign new users the "Researcher" role.

app/lib/uniprot_api.js
=> Fixed an issue where Uniprot would fail to extract subspecies taxon names

app/controllers/submission.js, test/controllers/submission_test.js
=> Submission metadata

app/lib/responses.js, app/services/logger.js, app/services/obo_importer/obo_importer.js, config/development.js, config/production.js, config/test.js, test_terms_fail.obo
=> changed debug to error for logging

app/controllers/submission.js, test/controllers/submission_test.js
Note that this is a non-scalable,  stop-gap solution for paginated sorting, and should be fixed once the system is being used. See #172
Closes #158
=> Submission list sorting

app/controllers/dev_only.js
The dev-only token endpoint was broken in #165
=> This was broken in a previous story

app/lib/responses.js, app/middleware/authentication.js, app/routes/submission.js, app/services/logger.js, config/test.js, test/controllers/authentication_test.js
Closes #98 
Also modified the logging output for tests, just to prevent the logger output from drowning out the test output.
=> Curator check

.gitignore, app/controllers/keyword.js
Adds basic support for returning eco keywords
=> Return evidence_code for eco keyword searches

app/controllers/submission.js, test/controllers/submission_test.js
This fixes the failing unit tests in #209. It also changes what information is returned about the submitter.
=> Fixes #209 failing tests

app/lib/annotation_submission_helper.js, app/services/export_data.js, app/services/export_data_cli.js, app/services/obo_importer/daemon.js, package.json
This pull request allows for exporting gene term annotations in a nightly data dump to resources/exports/ named by day. It uses the GAF file format. This closes #183.
Evidence With support is not included.
=> Basic automatic data export

app/controllers/submission.js, app/lib/annotation_submission_helper.js, app/models/evidence_with.js, app/models/gene_term_annotation.js, migrations/20171204020436_add_evidence_with.js, seeds/test/test_data.js, seeds/test/test_data.json, test/controllers/submission_test.js
Adds backend support for #185 evidence with saving and returning from the server.
=> Added support for evidence with on the backend

app/controllers/submission.js, package.json, test/controllers/submission_test.js
- Sort submissions by date
- Fix #208 submission tests
- Update ejs version in package.json
=> Fix submission sort

app/controllers/keyword.js, test/controllers/keyword_test.js
This fixes #205 for the backend.
=> Synonym search

app/services/export_data.js, app/services/export_data_cli.js
=> Added JSON export for comments on gene data

app/services/export_data.js
=> Data Export Tweaks

app/lib/annotation_submission_helper.js, app/lib/rna_central_api.js, app/services/export_data.js, app/services/obo_importer/daemon.js, bin/www
This starts the daemon with the web server in the same process, fixes a few of daemon/export bugs, fixes a lot of #255 minus the metadata, and fixes RNACentral that wasn't working due to a changed schema 🙄 .
=> Fix export issues and make daemon run correctly

appspec.yml, server-scripts/after-install
=> Move codedeploy landing dir #248

server-scripts/after-install
Fix script, ec2-user owns backend-deployment dir
=> Update codedeploy install script #248

app/controllers/submission.js, app/lib/annotation_submission_helper.js, app/services/export_data.js, migrations/20180227131237_add_ew_relation.js
This closes #241 by adding AND/OR support for evidence with storing, validation, and exporting
=> Adds evidence with relation support to the backend

.travis.yml, app/lib/annotation_submission_helper.js, app/lib/orcid_api.js, app/lib/tair_api.js, scripts/generate_orcid_file.js, seeds/test/test_data.json, test/controllers/gene_test.js, test/controllers/publication_test.js, test/controllers/submission_test.js, test/lib/models_test.js, test/lib/obo_importer_test.js, test/lib/submission_helper_test.js, test/lib/tair_api_test.js, test/lib/uniprot_api_test.js
- All tests should now be passing (assuming no metering and a reasonable response times of external apis)
- Travis will now run tests for the backend (only on the development branch)
=> Fixing tests

app/controllers/draft.js, app/controllers/submission.js
Make it so drafts are deleted when adding a new one and that they are deleted upon a proper submission.
=> Update drafts for backend

config/development.js, config/production.js, config/staging.js
=> Extend jwt lifespan

scripts/docker-setup.sh, scripts/run-docker.sh
starting to dockerize the db stuff.
=> docker scripts

app/controllers/annotation_search.js, app/routes/annotation_search.js, app/routes/api.js
The first iteration of the search algorithm is ready
=> Search by terms

app/controllers/search_export.js, app/routes/api.js, app/routes/search_export.js
This works by creating a temporary file when a user wants to export the information they've searched for.  This temporary file can then be downloaded by the frontend using the existing export API.  I edited the existing export to clear out these temporary files every night as part of the daily file creation.
=> Added backend functionality for exporting the results of a search

app/controllers/annotation_search.js
Things like GO:****** and PO:******* can be searched
=> Added keyword and method ID's to search 

knexfile.js
=> Login issue

app/controllers/annotation_search.js
=> search gene2 name
